# Generated by Django 4.1.7 on 2023-03-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('salary', models.IntegerField()),
                ('age', models.IntegerField()),
                ('joiningDate', models.DateField()),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('pQty', models.IntegerField()),
                ('pdescription', models.TextField(max_length=100, null=True)),
                ('pstatus', models.BooleanField(default=True)),
                ('pColor', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
