# Generated by Django 4.1.7 on 2023-03-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bureaucrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pName', models.CharField(max_length=100)),
                ('pSurname', models.CharField(max_length=100)),
                ('Dateofbirth', models.DateField(auto_now_add=True)),
                ('Exam', models.CharField(max_length=100)),
                ('joiningDate', models.DateField()),
            ],
            options={
                'db_table': 'bureaucrat',
            },
        ),
    ]
